name: Distribute

on:    
  push:
    branches: [ main ]
jobs:
  build:
    if: ${{ github.event.label.name == 'ReadyTest' }}
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode Version
      run: sudo xcode-select -switch /Applications/Xcode_12.5.1.app
      
      
    
