name: PullRequetLabeled

on:
  workflow_dispatch:
  pull_request:
    types: [ labeled ]
  push:
    branches: [ main ]
      
jobs:
  build:
    #if: github.event_name == 'workflow_dispatch'
    #if: ${{ github.event.label.name == 'ReadyTest' }}
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || github.event.label.name == 'ReadyTest' }}
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    
    - name: Run a one-line script
      run: echo Hello, world!
      
    - name: Select Xcode Version
      run: sudo xcode-select -switch /Applications/Xcode_12.5.1.app
