name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ synchronize, ready_for_review ]
    branches: [ main ]

jobs:
  build:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    
    - name: Select Xcode Version
      run: sudo xcode-select -switch /Applications/Xcode_12.5.1.app
      
#     - uses: actions/labeler@v3
#       with:
#         repo-token: "${{ secrets.GITHUB_TOKEN }}"
