name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ ready_for_review ]
    branches: [ main ]

jobs:
  build:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode Version
      run: sudo xcode-select -switch /Applications/Xcode_12.5.1.app
    
    - name: label swapping
      uses: actions/ready-for-review@1.0.0
      with:
        in-progress-label: 'my InProgress label'
        ready-for-review-label: 'my ReadyForReview label'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
